trigger:
  branches:
    include:
      - Staging
      - master

pool:
  name: Default

variables:
  repoUrl: 'https://github.com/yit-chun-wai/e08g03t05-odoo17.git'
  updateScript: '/home/is214/deploy-temp/update_code.sh'
  stagePath: '/home/is214/'

stages:

# =========================
# STAGING STAGE
# =========================
- stage: Staging
  displayName: Deploy to Staging
  condition: eq(variables['Build.SourceBranchName'], 'Staging')

  jobs:
  - deployment: DeployStaging
    environment: Staging
    strategy:
      runOnce:
        deploy:
          steps:

          # Sync code
          - task: SSH@0
            displayName: "Sync Code - Staging"
            inputs:
              sshEndpoint: 'ssh-odoo17-staging'
              runOptions: commands
              commands: |
                set -e
                echo "Deploying branch: $(Build.SourceBranchName)"
                cd $(stagePath)
                rm -rf deploy-temp *-odoo17

                git clone -b Staging $(repoUrl) --quiet
                mv *-odoo17 deploy-temp

                cd deploy-temp
                rm -f .DS_Store
                rm -rf .github

          # Run update script
          - task: SSH@0
            displayName: "Run Update Script - Staging"
            inputs:
              sshEndpoint: 'ssh-odoo17-staging'
              runOptions: commands
              commands: |
                echo "$(STAGINGUSERPASSWORD)" | sudo -S -p '' chmod +x $(updateScript)
                echo "$(STAGINGUSERPASSWORD)" | sudo -S -p '' $(updateScript)


# =========================
# PRODUCTION STAGE
# =========================
- stage: Production
  displayName: Deploy to Production
  condition: eq(variables['Build.SourceBranchName'], 'master')

  jobs:
  - deployment: DeployProduction
    environment: Production
    strategy:
      runOnce:
        deploy:
          steps:

          # Sync code
          - task: SSH@0
            displayName: "Sync Code - Production"
            inputs:
              sshEndpoint: 'ssh-odoo17-prod'
              runOptions: commands
              commands: |
                set -e
                echo "Deploying branch: $(Build.SourceBranchName)"
                cd $(stagePath)
                rm -rf deploy-temp *-odoo17

                git clone -b master $(repoUrl) --quiet
                mv *-odoo17 deploy-temp

                cd deploy-temp
                rm -f .DS_Store
                rm -rf .github

          # Run update script
          - task: SSH@0
            displayName: "Run Update Script - Production"
            inputs:
              sshEndpoint: 'ssh-odoo17-prod'
              runOptions: commands
              commands: |
                echo "$(STAGINGUSERPASSWORD)" | sudo -S -p '' chmod +x $(updateScript)
                echo "$(STAGINGUSERPASSWORD)" | sudo -S -p '' $(updateScript)