trigger:
  branches:
    include:
      - Staging
      - master

pool:
  name: Default

variables:
  repoUrl: 'https://github.com/souravb-smu/odoo17.git'
  updateScript: '/home/azureuser/deploy-temp/update_code.sh'
  stagePath: '/home/azureuser/'

stages:

# =========================
# STAGING STAGE
# =========================
- stage: Staging
  displayName: Deploy to Staging
  condition: eq(variables['Build.SourceBranchName'], 'Staging')

  jobs:
  - deployment: DeployStaging
    environment: Staging
    strategy:
      runOnce:
        deploy:
          steps:

          # Sync code
          - task: SSH@0
            displayName: "Sync Code - Staging"
            inputs:
              sshEndpoint: 'ssh-odoo17'
              runOptions: commands
              commands: |
                set -e
                echo "Deploying branch: $(Build.SourceBranchName)"
                cd $(stagePath)
                rm -rf deploy-temp *-odoo17

                git clone -b Staging $(repoUrl) --quiet
                mv *-odoo17 deploy-temp

                cd deploy-temp
                rm -f .DS_Store
                rm -rf .github

          # Run update script
          - task: SSH@0
            displayName: "Run Update Script - Staging"
            inputs:
              sshEndpoint: 'ssh-odoo17'
              runOptions: commands
              commands: |
                echo "$(STAGINGUSERPASSWORD)" | sudo -S -p '' chmod +x $(updateScript)
                echo "$(STAGINGUSERPASSWORD)" | sudo -S -p '' $(updateScript)


# =========================
# PRODUCTION STAGE
# =========================
- stage: Production
  displayName: Deploy to Production
  condition: eq(variables['Build.SourceBranchName'], 'master')

  jobs:
  - deployment: DeployProduction
    environment: Production
    strategy:
      runOnce:
        deploy:
          steps:

          # Sync code
          - task: SSH@0
            displayName: "Sync Code - Production"
            inputs:
              sshEndpoint: 'ssh-odoo17-production'
              runOptions: commands
              commands: |
                set -e
                echo "Deploying branch: $(Build.SourceBranchName)"
                cd $(stagePath)
                rm -rf deploy-temp *-odoo17

                git clone -b master $(repoUrl) --quiet
                mv *-odoo17 deploy-temp

                cd deploy-temp
                rm -f .DS_Store
                rm -rf .github

          # Uncompress SQL on VM
          - task: SSH@0
            displayName: "Uncompress odoo.sql.gz on VM"
            inputs:
              sshEndpoint: 'ssh-odoo17-production'
              runOptions: commands
              commands: |
                set -e
                cd $(stagePath)/deploy-temp/
                echo "Uncompressing odoo.sql.gz..."
                gunzip -c $(tempDeploy)/odoo.sql.gz > $(tempDeploy)/odoo.sql
                echo "Uncompress complete: $(stagePath)/deploy-temp/odoo.sql"

          # Restore Database
          - task: SSH@0
            displayName: "Restore Database"
            inputs:
              sshEndpoint: 'ssh-odoo17-production'
              runOptions: commands
              commands: |
                set -e
                echo "$(STAGINGUSERPASSWORD)" | sudo -S -p '' cp /home/azureuser/deploy-temp/restore_db.sh /tmp/
                echo "$(STAGINGUSERPASSWORD)" | sudo -S -p '' cp /home/azureuser/deploy-temp/odoo.sql /tmp/

                echo "$(STAGINGUSERPASSWORD)" | sudo -S -p '' chmod +x /tmp/restore_db.sh
                echo "$(STAGINGUSERPASSWORD)" | sudo -S -p '' chmod 644 /tmp/odoo.sql

                echo "$(STAGINGUSERPASSWORD)" | sudo -S -p '' -u postgres /tmp/restore_db.sh "odoo17" "odoo" "/tmp/odoo.sql"

          # Run update script
          - task: SSH@0
            displayName: "Run Update Script - Production"
            inputs:
              sshEndpoint: 'ssh-odoo17-production'
              runOptions: commands
              commands: |
                echo "$(STAGINGUSERPASSWORD)" | sudo -S -p '' chmod +x $(updateScript)
                echo "$(STAGINGUSERPASSWORD)" | sudo -S -p '' $(updateScript)
