services:
  web:
    image: jiaying0811/odoo17:latest
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./filestore:/var/lib/odoo/filestore
      - odoo-web-data:/var/lib/odoo
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: esm-odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_USER: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
      - ./odoo.sql.gz:/docker-entrypoint-initdb.d/odoo.sql.gz
volumes:
  odoo-web-data:
  odoo-db-data: