apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-pvc
  namespace: odoo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
        - name: odoo
          image: jiaying0811/odoo17:latest
          ports:
            - containerPort: 8069
          env:
            - name: HOST
              value: postgres
            - name: PORT
              value: "5432"
            - name: USER
              value: odoo
            - name: PASSWORD
              value: odoo
          volumeMounts:
            - name: odoo-storage
              mountPath: /var/lib/odoo
      volumes:
        - name: odoo-storage
          persistentVolumeClaim:
            claimName: odoo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: odoo
  namespace: odoo
spec:
  type: LoadBalancer
  selector:
    app: odoo
  ports:
    - port: 80
      targetPort: 8069
